services:
  mqtt:
    build:
      context: ./
      dockerfile: ./mqtt.Dockerfile
    image: openmoxie/openmoxie-mqtt:${OPENMOXIE_VERSION:-latest}
    ports:
      - "8883:8883"
    volumes:
      - ./local/work:/mosquitto/log
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: openmoxie/openmoxie-server:${OPENMOXIE_VERSION:-latest}
    ports:
      - "8001:8000"
    volumes:
      - ./local/work:/app/site/work
    command: ["bash", "start_server.sh"]
    depends_on:
      - mqtt
  postgres:
    image: postgres:17-alpine
    ports:
      - "0:5432"
    environment:
      POSTGRES_USER: openmoxie
      POSTGRES_PASSWORD: openmoxie
      POSTGRES_DB: openmoxie
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
